apiVersion: v2
name: grafana
description: A Helm chart for Grafana

# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
type: application

# The chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# Version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: "1.0"

dependencies:
- name: loki
  version: 5.42.2
  repository: https://grafana.github.io/helm-charts
- name: grafana
  version: 7.3.0
  repository: https://grafana.github.io/helm-charts
- name: opentelemetry-collector
  version: 0.80.1
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
# - name: vault-secrets
#   version: 1.1.12
#   repository: https://charts.design-and-engineering.co.uk