---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-argocd-sa
  namespace: argocd
  # annotations:
  #   iam.amazonaws.com/role: arn:aws:iam::123456789012:role/MyRole

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argocd
  name: argocd-grafana-access-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"] # Add the resources you want to grant access to
  verbs: ["get", "list", "watch", "create", "update", "delete"] # Add the verbs you want to allow

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-role-binding
  namespace: argocd
subjects:
- kind: ServiceAccount
  name: my-argocd-sa
  namespace: argocd
roleRef:
  kind: Role
  name: argocd-grafana-access-role
  apiGroup: rbac.authorization.k8s.io
